from . import ackley
from . import bentcigar
from . import bohachevsky
from . import chichinadze
from . import dropwave
from . import fms
from . import griewank
from . import holzman
from . import levy
from . import matyas
from . import pow
from . import powell
from . import rastrigin
from . import rosenbrock
from . import rothellipsoid
from . import schaffer
from . import schaffer2
from . import schwefel
from . import sphere
from . import styblinskitang
from . import sumofdifferentpowers
from . import threehumps
from . import zakharov
from . import zettle
